### ISSUE TITLE
Accessing parent collection during view model initialization

### ISSUE THREAD

**Issue by ncortines** [kmalakoff/knockback#135]
Hi,

I have the following construction which allows to determine if any item in the parts collection is duplicated:

```javascript
var that = this;
this.parts = kb.collectionObservable(orderParts, {
    view_model: function (orderPart) {
    	this.partNumber = kb.observable(orderPart, 'number');
    	this.isDuplicated = ko.computed(function () {
			return that.parts().filter(function (part) {
				return part.partNumber() === this.partNumber();
			}, this).length > 1;		
		}, this);
    }
}
```

This construction works fine if orderParts is initially empty. However it will fail if it initially contains records because of the that.parts() reference. that.parts does not have a reference to the collection by the time the view models are initialized.

I see three possible solutions to this problem:
* Declaring isDuplicated as an observable and update it with a function from outside the collection (a subscription to it for example). This is for me the least desirable solution.
* Having knockback to pass a collection reference to the view model constructor function. Something along the lines:
```javascript
var that = this;
this.parts = kb.collectionObservable(orderParts, {
    view_model: function (orderPart, option, parts) {
    	this.partNumber = kb.observable(orderPart, 'number');
    	this.isDuplicated = ko.computed(function () {
			return parts().filter(function (part) {
				return part.partNumber() === this.partNumber();
			}, this).length > 1;		
		}, this);
    }
}
```
* Having knockback to pass the collection reference to parts before the view models are initialized. This is the most desirable solution for me because does not require changes to the above code.

Thanks!!
Juan Cortines

**Comment by kmalakoff** [comment]
I started implementing the tests and realized that there is a problem in the logic. 

During the creation of view models, all of the other view models will not yet exist so the filter won't work on the collection observable. Also, it would create a dependency that may get fired many times as each model is added.

I think it is best if you follow one of your suggested work arounds. Sorry!

**Comment by ncortines** [comment]
What about adding an option to the *kb.collectionObservable* factory which would instantiate the initial ViewModel instances asynchronously after the new *kb.collectionObservable* instance has been returned?

**Comment by kmalakoff** [comment]
I understand why you are asking for this, but I'm not sure about adding the complexity / control flow of an asynchronous create. I would rather pass the collection observable, but it would need to be fully initialized and would run into the problem I mentioned.

Is there a way to solve this from the outside? eg. subclassing the collection observable and adding an isDuplicate method then using it in the view $parent?

If you really want the async flow, I will accept a pull request with tests.

**Comment by kmalakoff** [comment]
I was thinking....couldn't you just solve it by breaking it into two steps:

```
var that = this;
this.parts = kb.collectionObservable(new Backbone.Collection(), {
    view_model: function (orderPart) {
        this.partNumber = kb.observable(orderPart, 'number');
        this.isDuplicated = ko.computed(function () {
            return that.parts().filter(function (part) {
                return part.partNumber() === this.partNumber();
            }, this).length > 1;        
        }, this);
    }
}

this.parts.collection().reset(orderParts.models);
```

**Comment by ncortines** [comment]
Hmm I guess I could, didn't think about it, but I get the feeling that *parts* would not react to newly added or removed items in *orderParts*

**Comment by kmalakoff** [comment]
Me too. I just thought of it!

Yes, the isDuplicated observable will respond to added and removed models. When you access a collectionObservable like that.parts(), Knockout creates a dependency for when models are added and removed from the underlying collection.

Hopefully, this solves it!

**Comment by ncortines** [comment]
Well, I see that indeed everything works as expected at the moment of creating *parts*: Existing items can properly determine its *isDuplicated* property.

However it seems like, as suspected, *parts* does not react to newly added items in *orderParts*

Please see my example: http://codepen.io/ncortines/pen/XmbEoo?editors=101

Items number "3" and "4" are not displayed.

**Comment by kmalakoff** [comment]
Sorry for the confusion. You are actually adding "3" and "4" to a different collection than in the collection observable.

This works:

```
var that = this;

orderParts = new Backbone.Collection();

orderParts.add({
  number: 1
});

orderParts.add({
  number: 2
});

orderParts.add({
  number: 2
});

this.parts = kb.collectionObservable({
  view_model: function (orderPart) {
    this.partNumber = kb.observable(orderPart, 'number');
    this.isDuplicated = ko.computed(function () {
      return that.parts().filter(function (part) {
        return part.partNumber() === this.partNumber();
      }, this).length > 1;        
    }, this);
  }
});
this.parts.collection(orderParts);

ko.applyBindings();

orderParts.add({
  number: 3
});

orderParts.add({
  number: 4
});
```

Or you could do it like (but I suspect you prefer the first way to use the right collection):

```
var that = this;

orderParts = new Backbone.Collection();

orderParts.add({
  number: 1
});

orderParts.add({
  number: 2
});

orderParts.add({
  number: 2
});

this.parts = kb.collectionObservable(new Backbone.Collection(), {
  view_model: function (orderPart) {
    this.partNumber = kb.observable(orderPart, 'number');
    this.isDuplicated = ko.computed(function () {
      return that.parts().filter(function (part) {
        return part.partNumber() === this.partNumber();
      }, this).length > 1;        
    }, this);
  }
});

this.parts.collection().reset(orderParts.models);

ko.applyBindings();

this.parts.collection().add({
  number: 3
});

this.parts.collection().add({
  number: 4
});
```

Hopefully, this is all clear! Thanks for your support....

**Comment by ncortines** [comment]
Nice! That (the first version) is exactly what I needed.

Thanks!
Juan
