### ISSUE TITLE
Calling function on viewmodel embedded in collection.

### ISSUE THREAD

**Issue by mlarsson** [kmalakoff/knockback#141]
Hello Kevin and others

 I'm having a problem with the code below:

```javascript

var Model = Backbone.RelationalModel.extend({
    url: '...'
});


var ListModel = Backbone.RelationalModel.extend({
    url: '...',
    relations: [{
            type: Backbone.HasMany,
            key: 'coll',
            relatedModel: Model
        }
    ]
});

ModelViewModel = kb.ViewModel.extend({
    constructor: function (model) {
        kb.ViewModel.prototype.constructor.apply(this, arguments);
        var self = this;
        self.model = model;

        self.cancel = function () {
            this.destroy();
        }.bind(model);
    }
});

var listModel = new ListModel();

var viewModel = new kb.viewModel(listModel, {
    factories: {
        'coll.models': ModelViewModel
    }
});


ko.applyBindings(view_viewModel, $('#some-div')[0]);


<tbody data-bind="foreach: coll">
    <tr>
        <td>...</td>
        <td><button data-bind="click: cancel" class="btn btn-danger">Cancel</button></td>
    </tr>
</tbody>

```

What I want is to be able to call destroy on the particular model in coll but no matter what I do the call is always made on the first element added to the list. That is: cancel is always called on listModel.coll()[0] no matter what.

I have tried a million things but nothing seems to work. Hope you are able to help me.

Kind regards Morten

**Comment by kmalakoff** [comment]
Hi Morten,

I took a look at was able to get it working by wrapping your tbody tag in a table tag

```
  <div id="some-div">
    <table>
      <tbody data-bind="foreach: coll">
          <tr>
              <td>...</td>
              <td><button data-bind="click: cancel" class="btn btn-danger">Cancel</button></td>
          </tr>
      </tbody>
    </table>
  </div>
```

It looks like the browser (I only tested on Chrome) stripped out the tbody tag if it wasn't enclosed in a table tag.

Also, I noticed you stored the model on the view model. Knockback actually already does this for you so are stomping on an observable named 'model' that is expected internally in Knockback and you can simplify your code to:

```
ModelViewModel = kb.ViewModel.extend({
    constructor: function (model) {
        kb.ViewModel.prototype.constructor.apply(this, arguments);
        this.cancel = function () {this.model().destroy();}
    }
});
``` 

Let me know if this doesn't work for you.

**Comment by mlarsson** [comment]
Thank you very much. That solved my issue.
