### ISSUE TITLE
Having more than one viewmodel associated to a model property

### ISSUE THREAD

**Issue by mlarsson** [kmalakoff/knockback#142]
Hello Kevin

I have a small problem and can't find a solution anywhere on the web. So I hope you have a few minutes to help me out?

Basically I'm building an application with more than one viewmodel associated to each model. Until now I have had no problems with this as long as each viewmodel is attached to distinct root elements but now I face a problem. Having two viewmodels that both create kb.observables on the same model property is not working. Here is an example:

```javascript
var model = Backbone.Model.extend({});

var view_model1 = new ViewModel1(model);
ko.applyBindings(view_model, $('#a-section')[0]);

var view_model2 = new ViewModel2(model);
ko.applyBindings(view_model2, $('#another-section')[0]);

```
where the viewModels are:
```javascript
 var ViewModel1 = kb.ViewModel.extend({
        constructor: function (model) {
            this.foo = kb.observable(model, 'foo');
            ...
        }
 });

 var ViewModel2 = kb.ViewModel.extend({
        constructor: function (model) {
            this.foo = kb.observable(model, 'foo');
            ...
        }
 });
```

The problem is that the two-way binding of 'foo' in the second viewmodel isn't working. E.g.

```javascript
> view_model1.foo(12345)
> view_model1.foo() > 12345 (right value)
> model.get('foo') > 12345 (right value)
> view_model2.foo() > null (still old value)
> model.set('foo', 5432);
> model.get('foo') > 5432 (right value)
> view_model1.foo() > 5432 (right value)
> view_model2.foo() > null (still old value)
```

From my point of view this should be possible in MVVM as it is required to enable developer to have different views showing the same model in different ways.

Hope that you are able to help me along with this problem.

Kind regards
Morten

**Comment by kmalakoff** [comment]
Hi Morten,

This should absolutely work. Did you try something like this?

```
 var ViewModel1 = kb.ViewModel.extend({
        constructor: function (model, options) {
            kb.ViewModel.prototype.constructor.call(this, model, options, {requires: ['foo']});
            ...
        }
 });

 var ViewModel2 = kb.ViewModel.extend({
        constructor: function (model, options) {
            kb.ViewModel.prototype.constructor.call(this, model, options, {requires: ['foo']});
            ...
        }
 });
```

If that doesn't work, can you please transfer your code into a test case so I can debug? Just use knockback/test/issues/issue141 as reference. You can do a pull request and I'll dig in.
