### ISSUE TITLE
how to define parent and child relationship in advanced the view model.

### ISSUE THREAD

**Issue by akhilclarion** [kmalakoff/knockback#143]
Hi Kevin,

i am very new to knockback.js. i found, this is great tool work with knockout.js and backbone.js.

but i am straggling with understanding, please help me out.

i have parentview and  childview.
Parentview contains product information.
Childview contains details of product.

i will bind only child view like this, i should able to access parent view.
ko.applyBindings(Childview, $('#Childview')[0]);

And please provide tip on debugging the code.

**Comment by kmalakoff** [comment]
Nice to meet you. 

I think there are multiple answers to your question and a lot of it comes down to application and view architecture choices.

For example, you could create a view model with all of the information for both views or you could create a view model for each view.

Combined view model
```
class ProductViewModel extends kb.ViewModel
  constructor: (model, options) ->
     super(model, options, {requires: ['info1', 'info2', 'detail1', 'detail2']})
```

Separate view models
```
class ProductDetailsViewModel extends kb.ViewModel
  constructor: (model, options) ->
     super(model, options, {requires: ['detail1', 'detail2']})

class ProductInformationViewModel extends kb.ViewModel
  constructor: (model, options) ->
     super(model, options, {requires: ['info1', 'info2']})
    @details = new ProductDetailsViewModel(model)
```

The you can use the [knockout template binding](http://knockoutjs.com/documentation/template-binding.html) and the data property to pass whichever view model you need to the view to be rendered. 

Let me know if this answers your question.

**Comment by akhilclarion** [comment]
thanks for your efforts.

So soon, i will come back with new query.
