### ISSUE TITLE
Easiest way to require knockback/knockout on client?

### ISSUE THREAD

**Issue by wasd171** [kmalakoff/knockback#144]
Hi!

I can't get kb/ko to work with a build system. I've tried browserify and webpack (for some reason your webpack recipe doesn't work for me) with no luck. I'm using npm version of these modules.

So how do I require them (except with an ugly CDN link in my HTML code, which works great but is a wrong way, in my opinion)?

Thanks

P. S. Suddenly requiring only kb works! ko is required automatically. Don't get how to change ko name though, but that's a minor problem. Hope it helps somebody.

**Comment by kmalakoff** [comment]
I've tried this using the webpack documentation. It looks like with npm you need to install the modules at the top level (it looks like webpack couldn't find the nested node_modules):

$ npm install knockback knockout backbone underscore jquery --save-dev

Maybe webpack has done this resolution scheme given the upcoming npm@3.x changes to flatten the installed modules.
