### ISSUE TITLE
LocalStorage problems

### ISSUE THREAD

**Issue by wasd171** [kmalakoff/knockback#145]
Hi

I experience the same problem, as described here http://stackoverflow.com/questions/15111361/backbone-localstorage-saves-but-does-not-fetch-collection-using-knockback

For some reason knockback can't see localstorage backbone collection. If I set it manually, it works

P.S. Thanks for the great lib :-)

**Comment by kmalakoff** [comment]
I've added a test case and it seems to work just fine - if you call fetch on the collection, it gets populated with the models and the collection observable renders the view models.

Try it out and let me know what is not working: https://github.com/kmalakoff/knockback/blob/master/test/issues/issue145

**Comment by wasd171** [comment]
I'm so sorry - it was my problem. Everything works fine!

**Comment by kmalakoff** [comment]
Good to hear
