### ISSUE TITLE
AmpersandJS support

### ISSUE THREAD

**Issue by wasd171** [kmalakoff/knockback#147]
Is it possible to use AmpersandJS models/collections with Knockback?

**Comment by kmalakoff** [comment]
I haven't tried, but if you want to quickly check, you could load them in the browser and replace window.Backbone with ampersand.

**Comment by wasd171** [comment]
AmpersandJS has a different structure, many independent modules. kb.ViewModel works fine, but looks like kb.collectionObservable is broken

**Comment by abradley2** [comment]
Ampersand collections: `mainIndex` specifies the attribute used in `.get`  
https://github.com/AmpersandJS/ampersand-collection/blob/master/ampersand-collection.js#L164

Backbone collections: `modelId` specifies the attribute used in `.get`  

Not sure if this is particularly applicable to Knockback, but this discrepancy alone is enough to mean Ampersand Collections are not guaranteed to be usable as drop in replacements for Backbone Collections.

**Comment by kmalakoff** [comment]
You should be able to stick the model and collection in an object to manually aggregate them.

As for ids, I don't think they are referenced anywhere.

I'd give it a shot and see if it works.

**Comment by wasd171** [comment]
This works as a partial replacement for `kb.collectionObservable`
```
@collectionObservable = (@collection, @options) ->
	return ko.observableArray( @collection.map( (model) => new @options.view_model(model) ) )
```

**Comment by kmalakoff** [comment]
Yeah, that's definitely a possible approximation. It won't give you two-way syncing though.

I'll take a look at this in my spare time to see if I can officially support ampersand.

**Comment by kmalakoff** [comment]
Closed due to inactivity
