### ISSUE TITLE
collection filters and viewModel caching

### ISSUE THREAD

**Issue by far-blue** [kmalakoff/knockback#149]
Hello :)

I have a collectionObservable backed by a backbone collection with over 200 model instances in it and I'm using the filter functionality to allow the customer to search by description etc. I've noticed that when the search results change the viewModels are being destroyed and re-created which is making things very slow for the UI (esp. when the customer clears a filter and all 200+ viewModels need to be shown).

Is there some way to cache the viewModels even though they are not present in the collectionObservable? I've had a look at kbStore but I can't make sense of how to use it or whether it is the best option for this problem.

Also, do you know whether knockback will emit events for each viewModel added to or removed from the observable collection or whether it just emits one event once all the viewModels have been updated?

**Comment by kmalakoff** [comment]
Hello! 

By default, collection observables retain and reuse view models during the root of the graph's lifetime (I say graph because Knockback automatically handles cyclical model graphs). This is done [behind the scenes](https://github.com/kmalakoff/knockback/blob/master/src/core/collection-observable.coffee#L415) and shouldn't be necessary to use the store directly.

How are you implementing the filter? Either way, you should probably be doing something that doesn't actually edit the collection observable, but have a computed that filters it:

```
class MyViewModel {
  constructor() {
    this.things = kb.collectionObservable();

    this.filter = kb.observable(/* filter */);
    this.filteredThings = kb.computed(() => {
      return this.things().filter(thing => thing.name() === this.filter());
    });
  }
}
```

Does this help?

**Comment by far-blue** [comment]
Things in our actual code are rather complicated but basically we are first creating a collectionObservable from a model collection:

`packages = kb.collectionObservable(new PackageCollection(), {view_model: PackageRowView});`

and then applying filters like so:

`packages.filters(filterFunctions)`

where filterFunctions is an array of filter functions (each of which returns true or false). When the required filters change or the state of a filter changes (e.g. the text being searched for) then we update the filterFunctions array and re-apply it.

We couldn't get it to work passing an observableArray of functions so the array is a normal one.

What we find as we apply and change filters is that the viewModel instances for the models are being destroyed and created.

**Comment by kmalakoff** [comment]
Your approach should work unless the regression has occurred with deferred updates. I've added it to my list to look at.

What about trying my suggestion of implementing filters outside of the collection observable?

As for a lifecycle bug in the store, if you prepare a test case, I can look into it.

**Comment by far-blue** [comment]
I'll take a look next week, thank you for the suggestions :) I've poked around a bit more and I think the problem may not be the ViewModel being deleted but the viewModel instances backing the various ko components. When the viewModel is removed from the observable array it is also unlinked from the DOM and the DOM is cleaned up (which is perfectly reasonable). But this is causing all the component instances to also be disposed of which I think is what I'm seeing and is possibly also what makes putting all the ViewModels back on screen so slow.

I'll have a look at trying to use some sort of visibility flag instead to reduce the impact on the DOM.

Thanks again for you help :)

**Comment by kmalakoff** [comment]
That sounds like you've put your finger on the problem. Definitely elements would get removed and put back into the DOM as the filtering occurs.

**Comment by far-blue** [comment]
I've re-worked the filtering and used css to show/hide viewModels rather than ripping the data from the DOM and I can confirm it is significantly faster :) ViewModels are no longer being created and destroyed as they were before although we'd already agreed it was the components, not the ViewModels from the filtered Collection that were being deleted so I believe everything is working as expected.

Thank you for your pointers!

**Comment by kmalakoff** [comment]
@far-blue great to hear! Congratulations.
