### ISSUE TITLE
Knockout 3.4 deferred updates

### ISSUE THREAD

**Issue by far-blue** [kmalakoff/knockback#150]
Hello :) Could someone possibly tell me how well knockback works with deferred updates? I've tried turning them on in knockout 3.4 and it seems filters on observable collections are broken but does anyone know of other problems?

**Comment by kmalakoff** [comment]
I haven't used them yet. 

I'll run the tests with the latest Knockout and see if they are failing. Can you provide a code sample for how you are using them so I can add a test?

**Comment by far-blue** [comment]
Well, you basically just turn them on in KO 3.4: http://knockoutjs.com/documentation/deferred-updates.html

**Comment by kmalakoff** [comment]
Thanks for the information. So I need to test filters with deferredUpdates globally:

```
ko.options.deferUpdates = true;
```

On the filters, I'd suggest trying filtering outside the collection observable. It should be equivalent to inside but will be more in your control.

**Comment by chaozi712** [comment]
Hello kmalakoff, I am very interested in the deferred feature, is there any update on this?

**Comment by kmalakoff** [comment]
Closed due to inactivity
