### ISSUE TITLE
What's the state of support for LoDash 4?

### ISSUE THREAD

**Issue by far-blue** [kmalakoff/knockback#151]
Hello :)

Does anyone know the state of support for LoDash 4.x? They made quite a few breaking changes with 4.x - including removing 'thisArg' parameters from most methods.

**Comment by kmalakoff** [comment]
To try it out, just install from scratch and run the tests. 

Lodash version is floating (https://github.com/kmalakoff/knockback/blob/master/package.json#L79) so easy to find out.

**Comment by kmalakoff** [comment]
lodash 4.x seems to work fine with the automated tests.

**Comment by kmalakoff** [comment]
@far-blue I've published Knockback 1.2.0 with updates to support the simplifications from LoDash 4. Sorry for the delay...
