### ISSUE TITLE
Please consider officially supporting NestedTypes

### ISSUE THREAD

**Issue by far-blue** [kmalakoff/knockback#152]
Hello :)

We've been successfully using NestedTypes with KnockBack for a few months now and really like it as a replacement for Backbone. It handles nested models and has strict attribute typing which both work very well. Would it be hugely difficult to have your testing also run and test against NestedTypes as an alternative to Backbone?

**Comment by kmalakoff** [comment]
Very interesting! I personally do not have the time to implement this (just started a new company), but pull requests are definitely welcome!

The places you need to look to hook in the support and tests are:

https://github.com/kmalakoff/knockback/blob/master/config/test_groups.coffee#L16
https://github.com/kmalakoff/knockback/blob/master/src/core/kb.coffee#L220
https://github.com/kmalakoff/knockback/blob/master/src/core/index.coffee#L15

**Comment by kmalakoff** [comment]
Closed due to inactivity
