### ISSUE TITLE
Is there a way to observe an object attribute without it being converted to a ViewModel?

### ISSUE THREAD

**Issue by far-blue** [kmalakoff/knockback#154]
Hi :)

Is there a kb.observable() equiv. of the collection's "models_only" flag? I have some attributes of a model that are objects. I want my ViewModel's attribute to track the object changing but don't want a ViewModel. Currently I'm using the following but it would be nice if it was part of the kb package:

`function rawObservable(model, key)
    {
        var observer = kb.triggeredObservable(model, 'change:' + key);
        return ko.pureComputed(function() {
            observer();
            return model.get(key);
        });
    }
`

**Comment by kmalakoff** [comment]
Did you try a factory?

Maybe something like:

```
class MyViewModel extends kb.ViewModel
  constructor(model, options) ->
    super(model, options, {factories:
       key: {create: (model, options) -> return model; }
    })
```

**Comment by far-blue** [comment]
I'm not hot on coffeescript so just to clarify, I think the code above would be used to define a constructor for the attribute that would usually be turned into a ViewModel. Then when using kb.observable() you would supply that constructor which would then return the model directly rather than a viewModel created from it. Is that about right?

So I could define a generic 'don't make me into a ViewModel' ViewModel constructor and use that where I wanted the actual model.

**Comment by kmalakoff** [comment]
@far-blue Hmmm. I might not understand your use case. My assumption is that the observable is part of a ViewModel which i why I suggested a factory for the attribute in question.

Can you show me a little more context to your problem and explain why a factory is not a fit?

**Comment by kmalakoff** [comment]
Closed due to inactivity
