### ISSUE TITLE
Doc Needs to Be Updated

### ISSUE THREAD

**Issue by ZheyangSong** [kmalakoff/knockback#158]
Hi,

I'm going through this library and find out that the doc is out of date due to either not keeping up with the code evolution or something else... Would you mind to keep the API doc up-to-date? Also, would you like to add missing examples to those methods that don't have one? Thank you.

**Comment by kmalakoff** [comment]
@ZheyangSong the API has been pretty stable for a while. 

Feel free to list out the APIs that are missing examples and I can add examples.

**Comment by kmalakoff** [comment]
Closing due to lack of activitiy
