### ISSUE TITLE
"Cannot read property '_subscribable' of undefined" in kb.renderTemplate

### ISSUE THREAD

**Issue by noukenolife** [kmalakoff/knockback#159]
Hi. Currently, I am trying to use kb.renderTemplate to render the page view. But when I tried to load my page view, kb.renderTemplate gives an error, which is
```
Cannot read property '_subscribable' of undefined
```
I looked into the kb.renderTemplate implementation and tried to find out why this error occurs, and I ended up finding out that ko.contextFor(el.childNodes[0]) returns undefined, and ko.storedBindingContextForNode gets this undefined as an argument. 

Am I doing wrong, or is this the actual issue or bug in knockback?

**Comment by kmalakoff** [comment]
Not sure why this is happening. 

I've done a clean install and rerun the tests which seem to be passing: https://github.com/kmalakoff/knockback/blob/master/test/spec/core/core.tests.coffee#L41 so it probably isn't a change to the knockout API. I think the render template API might be something I supported from knockout 1.0 where they used jquery templates (I do not use this API myself).

Maybe you should use the more common API of `ko.applyBindings(view_model)` where there is an optional second parameter for the element. Alternatively, try getting your code working with plain old knockout and then add knockback afterwards for model-based view models - knockout provides hooks for looking up templates that you may need to configure using their documentation.

**Comment by j-yamamoto** [comment]
Oh. I should've mentioned that I used kb.renderTemplate for the navigation purpose. I looked at your knockback-navigations documentation below, and tried to use kb.renderTemplate as the documentation does.
http://kmalakoff.github.io/knockback-navigators/examples/pns_jq_kb.html

Then, I got the error that I showed you in the previous comment, and I still can't figure out how to solve this...

**Comment by noukenolife** [comment]
@kmalakoff 
Oh. I should've mentioned that I used kb.renderTemplate for the navigation purpose. I looked at your knockback-navigations documentation below, and tried to use kb.renderTemplate as the documentation does.
http://kmalakoff.github.io/knockback-navigators/examples/pns_jq_kb.html

Then, I got the error that I showed you in the previous comment, and I still can't figure out how to solve this...

**Comment by kmalakoff** [comment]
Yeah, that's really old code from 2012. I wouldn't recommend using it as a current reference. We moved over to using web components instead of templates in HTML.  

Like I suggested, I would recommend getting things working with knockout itself and then adding knockback since knockback only provides a thin layer on top of the ko.renderTemplate method. Alternatively, you could create a github repo and I can take a look.

Personally, I wouldn't recommend the approach that you are following and would look for up-to-date knockout examples on how they suggest to structure an application.

**Comment by j-yamamoto** [comment]
> Yeah, that's really old code from 2012. I wouldn't recommend using it as a current reference. We moved over to using web components instead of templates in HTML.
Oh I did not know about it. Then, I am going to fix my code to follow recommended approach you suggested.

Thank you so much. I really appreciate your extremely fast response.
Honestly, I am really having fun with using knockback, so please keep up the good work!

**Comment by noukenolife** [comment]
> Yeah, that's really old code from 2012. I wouldn't recommend using it as a current reference. We moved over to using web components instead of templates in HTML.

Oh I did not know about it. Then, I am going to fix my code to follow the recommended approach you suggested.

Thank you so much. I really appreciate your extremely fast response.
Honestly, I am really having fun with using knockback, so please keep up the good work!

**Comment by kmalakoff** [comment]
Great to hear. Good luck and let me know if you need any help/

**Comment by AndyCJ** [comment]
This issue is caused by: [KB: kb.coffee#L154](https://github.com/kmalakoff/knockback/blob/c611d7d9fda125efa1ed4cfcfbed0a6068ae803c/src/core/kb.coffee#L154)

In my case `el.childNodes` has three nodes, the first and last node are a newline "\n", with the second node being the root div from my template.

`ko.contextFor(el.childNodes[0])` returns undefined because "\n" isn't a valid node type.

[KO: bindingAttributeSyntax.js#L468](https://github.com/knockout/knockout/blob/d2a9e44c32ce2ce182dba99cc0138164fe9afc18/src/binding/bindingAttributeSyntax.js#L468)

[MDN: Node Types](https://developer.mozilla.org/en/docs/Web/API/Node/nodeType)

I'm loading my templates from script tags in the DOM.

**Comment by kmalakoff** [comment]
Strange. I haven't looked into how Knockout converts HTML to DOM elements, but if Knockout works, Knockback should. I'm assuming newline nodes are not valid DOM elements so might need to filter them before binding or to ask Knockout to do this for you.

Can I help with anything specifically?

**Comment by AndyCJ** [comment]
A naive solution appears to be looping over the `el.childNodes` and calling `ko.contextFor` on them.

`ko.contextFor` returns `undefined` for nodes it doesn't work with, so the loop can be stopped when the first node is found which doesn't return `undefined`.

But I suspect there's lots of edge cases waiting to prove that loop is inadequate.

Simply looping over the elements would be an improvement over just using the first though as the code currently does.

**Comment by kmalakoff** [comment]
It's been years since I looked at that code, but I'm pretty sure Knockout only allows for apply binding on one node. 

In Knockback, I believe that I extended beyond Knockout's single node constraint to create a new root node if an array is passed since it was a case that I sometimes encountered. The assumption is that the array of nodes are valid.

Can you fix your problem by just ensuring valid nodes are used in client code? If not, feel free to submit a fix with tests.

**Comment by AndyCJ** [comment]
I suspect it's a change in how the browsers list child nodes, they probably didn't used to list "\n" as a node.

I call `kb.renderTemplate` and that function in Knockback calls `ko.renderTemplate` passing in a `div` called `el`.

[kb.coffee#L150](https://github.com/kmalakoff/knockback/blob/c611d7d9fda125efa1ed4cfcfbed0a6068ae803c/src/core/kb.coffee#L150)

I have a template defined inside script tags:

    <script>
        <div>...</div>
    </script>
	
`ko.renderTemplate` takes everything between the script tags and puts it as a child of `el`.

    <div>
        <div>...</div>
    </div>

`el.childNodes` sees this as three nodes, `\n`, `<div>`, and `\n`.

`el.childNodes[0]` is "\n", which isn't a valid node type for `ko.contextFor`.

So I'm passing in "valid" HTML. I could fix it my side by remove all newlines, but that doesn't make the HTML more correct, though it should solve the issue.

This modification would mirror the current functionality, but should filter out the invalid nodes:

	// Private function in kb.coffee
	function getValidChildren(el) {
		var validChildren = [];
		
		for(var childIndex = 0; childIndex < el.childNodes.length; childIndex++) {
			var child = el.childNodes[childIndex];
			
			switch (node.nodeType) {
				case 1:
				case 8:
					validChildren.push(child);
					break;
			}
		}
		
		return validChildren;
	}
	
	// kb.coffee - Replace Lines: 151 - 154
	var validChildren = getValidChildren(el);
	
	if validChildren.length is 1 # do not return the template wrapper if possible
        el = validChildren[0]
    else if validChildren.length
		ko.storedBindingContextForNode(el, ko.contextFor(validChildren[0])) # ensure the context is passed up to wrapper

[kb.coffee#L151-L154](https://github.com/kmalakoff/knockback/blob/c611d7d9fda125efa1ed4cfcfbed0a6068ae803c/src/core/kb.coffee#L151-L154)

I might look at submitting a pull request this weekend, but I suspect it'll take a fair bit of effort to get a suitable development environment set up and to learn the basics of coffeescript.

This issue isn't affecting me any more as I've moved to handling the templating manually, but it should affect anyone who tries to use the default Knockout templating with Knockback.

**Comment by kmalakoff** [comment]
Understood and I appreciate all of the details. It should be just an npm install to get up and running, but coffescript may take more (you could put the code through a JS <-> CS converter).

I'll take a stab at this over the weekend to save you the time. If I understand correctly, I need to look at templates defined in script tags - I haven't looked at that approach for many years (we moved to web components, and before that used a client side module system to load templates). 

I might have need to send some questions if I cannot reproduce. I'm assuming this is a problem on the latest Chrome?

**Comment by kmalakoff** [comment]
@AndyCJ I've spent a few hours trying to reproduce your problem (a lot of the time was actually spent on upgrading to latest libraries so I needed to do it anyways), but haven't been able to reproduce it.

Can you make the test fail for me so I can fix it?

Here is the test: https://github.com/kmalakoff/knockback/blob/issue159/test/spec/issues/159.tests.coffee#L28

To run it, switch to the issue159 branch, run `npm install`, and run the test with `node_modules/.bin/gulp test-browsers`.

If you want to step through to try to fix it yourself, you need to change karma from a single run on PhantomJS to multi run in an actual browser using the comments here: https://github.com/kmalakoff/knockback/blob/issue159/config/karma/base-config.coffee#L16
 
Let me know if you have any questions...

**Comment by kmalakoff** [comment]
@AndyCJ I was able to reproduce in an AMD test suite so I'll post a fix soon!
