### ISSUE TITLE
inputValidator attaches required validator even if there is no required attribute

### ISSUE THREAD

**Issue by wolasss** [kmalakoff/knockback#160]
There is a bug in the latest release (1.2.0).  

Consider following scenario: 

`<textarea data-bind="value: $_message, validations: { someFn: function(){return false}}, inject: validation.inputValidator" name="test"></textarea>`

With such element, the validation object should only attach `someFn` validator. The result though is that the `kb.inputValidator` attaches also `required` validator even if there is no required attribute on the element. From what I have investigated the bug is introduced in the commit b7db9d2c665b5dc6004547429bfe36238fe09133. In `kb.inputValidator` you replaced `!el.getAttribute('required'))` with `_.isUndefined(el.getAttribute('required'))` which is not the case. 

The getAttribute function returns `null` if there is no such attribute and `_.isUndefined(null)` returns false. You should consider using `element.hasAttribute` function instead.

**Comment by wolasss** [comment]
If one has this issue, workaround for now is to "override" required validator if it is not desired:

`validations: { required: function(){return false}}`

**Comment by kmalakoff** [comment]
@wolasss thank you for tracing this down. I'll create a patch over the weekend.

**Comment by kmalakoff** [comment]
I've released this as part of 1.2.1. Enjoy!

**Comment by wolasss** [comment]
Thanks for such a quick fix @kmalakoff
