### ISSUE TITLE
Webpack 3+ and Knockback

### ISSUE THREAD

**Issue by sdalonzo** [kmalakoff/knockback#164]
Hey Kevin,

I'm sure this is a solved problem but I can't seem to find the answer. It seems like something that should be super easy.

When I install current Webpack (3.10), Knockout and Knockback with NPM, I cannot get Webpack to use my Knockout in the root of node_modules to satisfy Knockback's dependency, and I end up with 2 Knockout instances in my bundle. In addition to being inefficient, it makes other KO plugins unavailable (presumably getting attached to the other instance). I recognize that my issue is most likely in my Webpack config, but since your project is built with Webpack, I thought you might have some insight to offer.

(EDIT) - We're using an alias in webpack to resolve knockback to knockback-core, if that helps: 
    knockback: 'knockback/knockback-core'

Many thanks,
-steve

**Comment by kmalakoff** [comment]
Hi Steve, can you share your webpack config file so I can take a look?

**Comment by sdalonzo** [comment]
Hey Kevin,

I've been out the last few days, so sorry for the tardiness in getting back to you. I ended up figuring out the fix. For posterity, here's what I had to do:

`const KNOCKOUT_PATH =			path.resolve('./node_modules/knockout/build/output/knockout-latest.debug');`
and then set resolve.alias.knockout to that value.

-steve
